/* ====================================================
javascript sheet "data.js" for "Instagram clone"
Author: Annette Lasar
Date: July 2023
====================================================== */

let posts = [
  {
    user_icon: '../img/blond-girl-square.jpg',
    name: 'Wonderwoman',
    realName: 'Yvonne Dachtler',
    status: 'Beliebt',
    likes: 7198,
    liked: false,
    images: '../img/cat-in-garden.jpg',
    image_format: 'square',
    date: '20.07.2023',
    videos: '../videos/jane_trailer.mp4',
    comments: [],
  },

  {
    user_icon: '../img/bearded-man-square.jpg',
    name: 'Jesusisalive',
    realName: 'Peter Müller',
    status: 'Beliebt',
    likes: 5198,
    liked: false,
    images: '../img/sparrow.jpg',
    image_format: 'square',
    date: '01.07.2023',
    videos: '../videos/marienkaefer.mp4',
    comments: [],
  },

  {
    user_icon: '../img/indian-square.jpg',
    name: 'Nirwana Man',
    realName: 'Rajesh',
    status: 'Beliebt',
    likes: 250001,
    liked: false,
    images: '../img/taj-mahal.jpg',
    image_format: 'rectangular',
    date: '12.04.2023',
    videos: '../videos/hummel.mp4',
    comments: [],
  },

  {
    user_icon: '../img/business-woman-square.jpg',
    name: 'BirdLover',
    realName: 'Karin Reichelt',
    status: 'Beliebt',
    likes: 31124,
    liked: false,
    images: '../img/hummingbird_square.jpg',
    image_format: 'square',
    date: '18.01.2023',
    videos: '../videos/kraehe.mp4',
    comments: [],
  },

  {
    user_icon: '../img/redhaired-woman-square.jpg',
    name: 'Agility Club',
    realName: 'Maja Schmiedemüller',
    status: 'Beliebt',
    likes: 551,
    liked: false,
    images: '../img/labrador.jpg',
    image_format: 'rectangular',
    date: '17.06.2023',
    videos: '../videos/colin.mp4',
    comments: [],
  },

  {
    user_icon: '../img/portrait-woman-square.jpg',
    name: 'Lilyfee',
    realName: 'Amy Woodpecker',
    status: 'Beliebt',
    likes: 62898,
    liked: false,
    images: '../img/sushi.jpg',
    image_format: 'square',
    date: '13.11.2022',
    videos: '../videos/watt.mp4',
    comments: [],
  },

  {
    user_icon: '../img/crime-author-square.jpg',
    name: 'Crime Author',
    realName: 'Bob Schmiller',
    status: 'Beliebt',
    likes: 276733,
    liked: false,
    images: '../img/architecture-square.jpg',
    image_format: 'square',
    date: '27.05.2023',
    videos: '../videos/hunde.mp4',
    comments: [],
  },

  {
    user_icon: '../img/hooded-man-square.jpg',
    name: 'Rapper Boy',
    realName: 'Jonas Tillson',
    status: 'Beliebt',
    likes: 33481,
    liked: false,
    images: '../img/vulture.png',
    image_format: 'square',
    date: '14.05.2023',
    videos: '../videos/reiten.mp4',
    comments: [],
  },

  {
    user_icon: '../img/woman-with-mobile-square.jpg',
    name: 'Workaholic',
    realName: 'Sandra Helm',
    status: 'Beliebt',
    likes: 4891,
    liked: false,
    images: '../img/team.jpg',
    image_format: 'square',
    date: '20.04.2023',
    videos: '../videos/schaf.mp4',
    comments: [],
  },

  {
    user_icon: '../img/portrait-woman-square.jpg',
    name: 'Carmen',
    realName: 'Christiane Steigler',
    status: 'Beliebt',
    likes: 399841,
    liked: false,
    images: '../img/portrait-woman.jpg',
    image_format: 'rectangular',
    date: '17.03.2023',
    videos: '../videos/ballet.mp4',
    comments: [],
  },

  {
    user_icon: '../img/modern-cowboy-square.jpg',
    name: 'Modern Cowboy',
    realName: 'Peter Gehlert',
    status: 'Beliebt',
    likes: 411,
    liked: false,
    images: '../img/woman-with-boy-square.jpg',
    image_format: 'square',
    date: '20.07.2023',
    videos: '../videos/dressage.mp4',
    comments: [],
  },

  {
    user_icon: '../img/boss-square.jpg',
    name: 'The Boss',
    realName: 'Karsten Winter',
    status: 'Beliebt',
    likes: 532,
    liked: false,
    images: '../img/mortality.jpg',
    image_format: 'square',
    date: '20.07.2023',
    videos: '../videos/heidi_intro.mp4',
    comments: [],
  },
];
